### ISSUE TITLE
Suggestion: Allow empty requirements.txt file

### ISSUE THREAD

**Issue by janusheide** [welbornprod/requirementz#4]
Currently running on an empty file result in the following error: "Requirements file is empty." and and exitcode 1.

According to this: https://github.com/pypa/pip/issues/343 pip now allows for empty requirements files, so would be logical that the same behaivor is adopted here.

**Comment by cjwelborn** [comment]
You're right, I'll get on it. Thank you.

**Comment by cjwelborn** [comment]
`--list` will print nothing, and `exit(0)` so . Other features will report `'Requirements file is empty'` but still `exit(0)`, some of those may also be removed to help with scripting.

**Comment by janusheide** [comment]
Great! and Thanks, that sounds like it should do it for me, so much appreciated.

Do you plan to release the project? -currently I am installing from pypi.

**Comment by cjwelborn** [comment]
@janusheide I'll do another pypi version tonight. It was late when I got everything tested.

**Comment by janusheide** [comment]
perfect, looking forward to it. - and thanks again.

**Comment by cjwelborn** [comment]
@janusheide, just wanted to let you know that version [0.3.5 is on PyPi](https://pypi.org/project/Requirementz/) now. Empty file operations always return `0`, and for operations that wouldn't make since on an empty file, a message is printed to `stderr` so it can be easily ignored in scripts.

So:
```bash
requirementz -c 2>/dev/null && echo "Everything is okay, even if the file is empty."
```

Thanks for reporting the issue. It's officially closed now :).

**Comment by janusheide** [comment]
I upgraded to your new version and can confirm that is works as advertised. Thanks for quickly dealing with this.
